services:
- rabbitmq
- ts-admin-basic-info-service
- ts-admin-order-service
- ts-admin-route-service
- ts-admin-travel-service
- ts-admin-user-service
- ts-assurance-mongo
- ts-assurance-service
- ts-auth-mongo
- ts-auth-service
- ts-avatar-service
- ts-basic-service
- ts-cancel-service
- ts-config-mongo
- ts-config-service
- ts-consign-mongo
- ts-consign-price-mongo
- ts-consign-price-service
- ts-consign-service
- ts-contacts-mongo
- ts-contacts-service
- ts-delivery-mongo
- ts-delivery-service
- ts-execute-service
- ts-food-map-mongo
- ts-food-map-service
- ts-food-mongo
- ts-food-service
- ts-inside-payment-mongo
- ts-inside-payment-service
- ts-news-service
- ts-notification-mongo
- ts-notification-service
- ts-order-mongo
- ts-order-other-mongo
- ts-order-other-service
- ts-order-service
- ts-payment-mongo
- ts-payment-service
- ts-preserve-other-service
- ts-preserve-service
- ts-price-mongo
- ts-price-service
- ts-rebook-service
- ts-route-mongo
- ts-route-plan-service
- ts-route-service
- ts-seat-service
- ts-security-mongo
- ts-security-service
- ts-station-mongo
- ts-station-service
- ts-ticket-office-mongo
- ts-ticket-office-service
- ts-ticketinfo-service
- ts-train-mongo
- ts-train-service
- ts-travel-mongo
- ts-travel-plan-service
- ts-travel-service
- ts-travel2-mongo
- ts-travel2-service
- ts-ui-dashboard
- ts-user-mongo
- ts-user-service
- ts-verification-code-service
- ts-voucher-mysql
- ts-voucher-service